name: Build Arch Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # يسمح لك بتشغيل البناء يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build PKGBUILD
        uses: 2ndndnd/arch-makepkg-action@v3
        with:
          # إذا كان ملف PKGBUILD في المجلد الرئيسي، اتركها كما هي
          pkgdir: . 

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: ./*.pkg.tar.zst
